# Generated by Django 4.1.6 on 2023-02-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0028_alter_ctgia_size'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTDonHang',
            fields=[
                ('maCTDH', models.AutoField(primary_key=True, serialize=False)),
                ('giaMon', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('soLuong', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('maDH', models.AutoField(primary_key=True, serialize=False)),
                ('tongTien', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('ngayLap', models.DateTimeField(auto_now_add=True)),
                ('trangThaiMon', models.IntegerField(default=0)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
            ],
        ),
        migrations.RemoveField(
            model_name='giohang',
            name='maKH',
        ),
        migrations.DeleteModel(
            name='CTGioHang',
        ),
        migrations.DeleteModel(
            name='GioHang',
        ),
        migrations.AddField(
            model_name='ctdonhang',
            name='maDH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.donhang'),
        ),
        migrations.AddField(
            model_name='ctdonhang',
            name='maMon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mon'),
        ),
    ]
