# Generated by Django 4.1.6 on 2023-02-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_ctgia_size'),
        ('customer', '0001_initial'),
        ('cart', '0004_alter_donhang_trangthaidh'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTGioHang',
            fields=[
                ('maCTGH', models.AutoField(primary_key=True, serialize=False)),
                ('soLuong', models.IntegerField(default=1)),
                ('ctGia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ctgia')),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('maGH', models.AutoField(primary_key=True, serialize=False)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
            ],
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='maKH',
        ),
        migrations.DeleteModel(
            name='CTDonHang',
        ),
        migrations.DeleteModel(
            name='DonHang',
        ),
        migrations.AddField(
            model_name='ctgiohang',
            name='maGH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.giohang'),
        ),
        migrations.AddField(
            model_name='ctgiohang',
            name='maMon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mon'),
        ),
    ]
