# Generated by Django 4.1.6 on 2023-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_ctgiohang_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='giohang',
            name='trangThai',
            field=models.BooleanField(default=True),
        ),
    ]
