# Generated by Django 4.1.6 on 2023-02-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('maKH', models.AutoField(primary_key=True, serialize=False)),
                ('hoKH', models.CharField(max_length=10)),
                ('tenKH', models.CharField(max_length=10)),
                ('sdt', models.IntegerField(default=0)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('diaChi', models.CharField(max_length=50)),
            ],
        ),
    ]
