# Generated by Django 4.1.6 on 2023-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
