# Generated by Django 4.1.6 on 2023-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_mon_mota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='img'),
        ),
    ]
