# Generated by Django 4.1.6 on 2023-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_mon_hinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhmuc',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='dm'),
        ),
    ]
