# Generated by Django 4.1.6 on 2023-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_danhmuc_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhmuc',
            name='hinhAnh',
            field=models.ImageField(default=None, null=True, upload_to='dm'),
        ),
    ]
