# Generated by Django 4.1.6 on 2023-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_danhmuc_hinhanh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhmuc',
            name='hinhAnh',
        ),
        migrations.AddField(
            model_name='danhmuc',
            name='hinhAnhDM',
            field=models.ImageField(default=None, upload_to='dm'),
        ),
    ]
