# Generated by Django 4.1.6 on 2023-02-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_danhmuc_hinhanh_danhmuc_hinhanhdm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhmuc',
            name='hinhAnhDM',
        ),
    ]
