# Generated by Django 4.1.6 on 2023-02-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_danhmuc_hinhanhdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='hinhAnh',
            field=models.ImageField(default=None, null=True, upload_to='img'),
        ),
    ]
