# Generated by Django 4.1.6 on 2023-02-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_mon_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='hinhAnh',
            field=models.ImageField(default=None, upload_to='img'),
        ),
    ]
