# Generated by Django 4.1.6 on 2023-02-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_mon_hinhanh'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhmuc',
            name='hinhAnhDM',
            field=models.ImageField(default=None, upload_to='dm'),
        ),
        migrations.AddField(
            model_name='mon',
            name='gia',
            field=models.IntegerField(default=0),
        ),
    ]
