# Generated by Django 4.1.6 on 2023-02-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_danhmuc_hinhanhdm_mon_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhmuc',
            name='hinhAnhDM',
            field=models.ImageField(default=None, null=True, upload_to='dm'),
        ),
    ]
