# Generated by Django 4.1.6 on 2023-02-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_danhmuc_hinhanhdm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhmuc',
            name='hinhAnhDM',
        ),
    ]
