# Generated by Django 4.1.6 on 2023-02-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_mon_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='gia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
