# Generated by Django 4.1.6 on 2023-02-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_mon_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mon',
            name='gia',
        ),
    ]
