# Generated by Django 4.1.6 on 2023-02-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_mon_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon',
            name='gia',
            field=models.IntegerField(default=0),
        ),
    ]
