# Generated by Django 4.1.6 on 2023-02-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_danhmuc_hinhanhdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='gia',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
