# Generated by Django 4.1.6 on 2023-02-19 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_mon_gia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTGia',
            fields=[
                ('maGia', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('m', 'M'), ('l', 'L')], max_length=50)),
                ('giaSize', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('maMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mon')),
            ],
        ),
    ]
