# Generated by Django 4.1.6 on 2023-02-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_ctgia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgia',
            name='size',
            field=models.CharField(max_length=2),
        ),
    ]
