# Generated by Django 4.1.6 on 2023-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_ctgia_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgia',
            name='size',
            field=models.CharField(default='L', max_length=2),
        ),
    ]
