# Generated by Django 4.1.6 on 2023-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_ctgia_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgia',
            name='size',
            field=models.CharField(choices=[('m', 'M'), ('l', 'L')], max_length=2),
        ),
    ]
