# Generated by Django 4.1.6 on 2023-02-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_ctgia_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctgia',
            name='maMon',
        ),
        migrations.AddField(
            model_name='ctgia',
            name='maDM',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.danhmuc'),
        ),
    ]
