# Generated by Django 4.1.6 on 2023-02-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_ctgia_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctgia',
            name='maDM',
        ),
        migrations.AddField(
            model_name='mon',
            name='size',
            field=models.ForeignKey(default='M', on_delete=django.db.models.deletion.CASCADE, to='product.ctgia'),
        ),
    ]
