# Generated by Django 4.1.6 on 2023-02-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_mon_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mon',
            name='size',
        ),
    ]
