# Generated by Django 4.1.6 on 2023-02-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_remove_mon_size_mon_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mon',
            old_name='size',
            new_name='sizes',
        ),
    ]
