# Generated by Django 4.1.6 on 2023-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_rename_size_mon_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgia',
            name='size',
            field=models.CharField(default='L', max_length=2),
        ),
        migrations.AlterField(
            model_name='mon',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='product.ctgia'),
        ),
    ]
