# Generated by Django 4.1.6 on 2023-02-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_rename_sizes_mon_sizemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mon',
            old_name='sizeMon',
            new_name='sizes',
        ),
    ]
