# Generated by Django 4.1.6 on 2023-02-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_rename_sizes_mon_sizemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctgia',
            name='maDM',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='product.danhmuc'),
        ),
    ]
