# Generated by Django 4.1.6 on 2023-02-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_ctgia_madm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctgia',
            name='maDM',
        ),
    ]
