# Generated by Django 4.1.6 on 2023-03-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_ctdanhgia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='tenMon',
            field=models.TextField(max_length=50),
        ),
    ]
