# Generated by Django 4.1.6 on 2023-03-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('maKM', models.AutoField(primary_key=True, serialize=False)),
                ('tenKM', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('phantramKM', models.IntegerField(default=1)),
                ('ngayHetHan', models.DateTimeField()),
                ('trangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trangThaiDH',
            field=models.CharField(choices=[('0', 'Hủy'), ('1', 'Chưa xác nhận'), ('2', 'Đã xác nhận'), ('3', 'Đang chuẩn bị'), ('4', 'Đang vận chuyển'), ('5', 'Hoàn thành')], default=0, max_length=50),
        ),
    ]
