# Generated by Django 4.1.6 on 2023-03-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_khuyenmai_ngayhethan'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='maKM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.khuyenmai'),
        ),
    ]
