# Generated by Django 4.1.6 on 2023-03-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_donhang_makm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('maTT', models.AutoField(primary_key=True, serialize=False)),
                ('tenTT', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='donhang',
            name='maTT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.thanhtoan'),
        ),
    ]
