# Generated by Django 4.1.6 on 2023-03-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_donhang_trangthaidh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='quanhuyen',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='tinhtp',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='xaphuong',
        ),
        migrations.AlterField(
            model_name='donhang',
            name='diachi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
